import React from 'react';

interface InformationBandProps extends React.HTMLAttributes<HTMLDivElement> {
  color?: string;
  height?: number | string;
  style?: React.CSSProperties;
  className?: string;
  children?: React.ReactNode;
}

const InformationBand: React.FC<InformationBandProps> = ({
  color,
  height,
  style = {},
  className = '',
  children,
  ...props
}) => {
  // Base Tailwind classes
  const baseClasses = `
    w-full 
    flex 
    items-center 
    text-center 
    justify-center 
    text-sm 
    text-gray-800 
    px-2.5 
    py-1.5
    bg-blue-50
    border-b 
    border-blue-100
    shadow-sm
    font-medium
    transition-all
    duration-200
    hover:shadow-md
  `;

  // Handle custom color if provided, otherwise use default Tailwind
  const customStyle = color ? { backgroundColor: color } : {};

  // Handle custom height
  const heightStyle = height
    ? { height: typeof height === 'number' ? `${height}px` : height }
    : {};

  return (
    <div
      className={`${baseClasses} ${className}`}
      style={{
        ...customStyle,
        ...heightStyle,
        ...style,
      }}
      {...props}
    >
      {children || (
        <div className="flex items-center space-x-2">
          <svg
            className="w-4 h-4 text-blue-500"
            fill="currentColor"
            viewBox="0 0 20 20"
          >
            <path
              fillRule="evenodd"
              d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
              clipRule="evenodd"
            />
          </svg>
          <span>
            {' '}
            The flow of transaction from Activity to Factor represents the
            movement of value added generated by production activities to the
            factors of production (like labor and capital) as their earned
            income.
          </span>
        </div>
      )}
    </div>
  );
};

export default InformationBand;
